{
 "title": "CPU",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "утилизация CPU"
    }
   ]
  },
  {
   "title": "FreeMem",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Avail Space",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "Avail Space"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count without (cpu) (rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"system\"}[1m])) * on (instance) group_left(node_load1) node_load1\n",
     "legendFormat": "1m"
    },
    {
     "expr": "count without (cpu) (rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"system\"}[5m])) * on (instance) group_left(node_load5) node_load5",
     "legendFormat": "5m"
    },
    {
     "expr": "count without (cpu) (rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"system\"}[5m])) * on (instance) group_left(node_load15) node_load15",
     "legendFormat": "15m"
    }
   ]
  }
 ]
}